apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping-sockeye
spec:
  data: '{"name": "triggermesh"}'
  schedule: '*/1 * * * *'
  sink:
    ref:
      apiVersion: <API_VERSION>
      kind: <KIND>
      name: <NAME>
