apiVersion: v1
kind: Secret
metadata:
  name: ddapitoken
type: Opaque
stringData:
  apiKey: <your-api-key>

---
apiVersion: v1
kind: Secret
metadata:
  name: aws
type: Opaque
stringData:
  access_key_id: <your-access-key-id>
  secret_access_key: <your-secret-access-key>
