apiVersion: v1
kind: Secret
metadata:
  name: zendeskcreds
type: Opaque
stringData:
  token: <your-token>
  webhookPassword: <your-webhook-password>
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-target
type: Opaque
stringData:
  token: <your-token>
