apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: zendesk-slack
  name: zendesk-slack
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        metadata:
          name: zd-evnts
    - object:
        apiVersion: sources.triggermesh.io/v1alpha1
        kind: ZendeskSource
        metadata:
          name: zendesk-slack-source
        spec:
          email: <your-email>
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1
              kind: Broker
              name: zd-evnts
          subdomain: <your-subdomain>
          token:
            secretKeyRef:
              key: token
              name: zendeskcreds
          webhookPassword:
            secretKeyRef:
              key: webhookPassword
              name: zendeskcreds
          webhookUsername: demousr
    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Trigger
        metadata:
          name: transform-trigger
        spec:
          broker: zd-evnts
          filter:
            attributes:
              type: com.zendesk.ticket.created
          subscriber:
            ref:
              apiVersion: flow.triggermesh.io/v1alpha1
              kind: Transformation
              name: zd-slack-transformation
    - object:
        apiVersion: flow.triggermesh.io/v1alpha1
        kind: Transformation
        metadata:
          name: zd-slack-transformation
        spec:
          context:
            - operation: add
              paths:
                - key: type
                  value: com.slack.webapi.chat.postMessage
          data:
            - operation: store
              paths:
                - key: $url
                  value: ticket.url
                - key: $author
                  value: current_user.email
            - operation: delete
              paths:
                - key: null
            - operation: add
              paths:
                - key: text
                  value: >-
                    $author has created a new Zendesk
                    Ticket: $url
                - key: channel
                  # Replace this with your slack channel.
                  value: <your-slack-channel-here>
    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Trigger
        metadata:
          name: tm-slack
        spec:
          broker: zd-evnts
          filter:
            attributes:
              type: com.slack.webapi.chat.postMessage
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: SlackTarget
              name: tm-slack
    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: SlackTarget
        metadata:
          name: tm-slack
        spec:
          token:
            secretKeyRef:
              key: token
              name: slack-target
