apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  name: zendesk-zendesk-sentiment
  annotations:
    bridges.triggermesh.io/name: zendesk-zendesk-sentiment
    bridges.triggermesh.io/description: >-
      This Bridge reacts to the creation of Zendesk Tickets and performs a
      sentiment analysis of those Tickets via AWS Comprehend. The result
      of this sentiment analysis is then used to tag those new Tickets.
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        metadata:
          name: events
      options:
        enableResync: false
    - object:
        apiVersion: sources.triggermesh.io/v1alpha1
        kind: ZendeskSource
        metadata:
          name: zendesk
        spec:
          email: <your-email>
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1
              kind: Broker
              name: events
          subdomain: <your-subdomain>
          token:
            valueFromSecret:
              key: token
              name: zendeskcreds
          webhookPassword:
            valueFromSecret:
              key: webhookPassword
              name: zendeskcreds
          webhookUsername: <your-username>
      options:
        enableResync: false
    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Trigger
        metadata:
          name: transform-sentiment-tag
        spec:
          broker: events
          filter:
            attributes:
              type: com.zendesk.ticket.created
          subscriber:
            ref:
              apiVersion: serving.knative.dev/v1
              kind: Service
              name: transform-sentiment-tag
      options:
        enableResync: false
    - object:
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          labels:
            serving.knative.dev/visibility: cluster-local
          name: transform-sentiment-tag
        spec:
          template:
            spec:
              containers:
                - env:
                    - name: LANGUAGE
                      value: en
                    - name: AWS_REGION
                      value: ""
                  envFrom:
                    - secretRef:
                        name: awscomprehend
                  image: >-
                    gcr.io/triggermesh/bridge-examples/zendesk-zendesk-transform-sentiment-tag
      options:
        enableResync: false
    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Trigger
        metadata:
          name: zendesk
        spec:
          broker: events
          filter:
            attributes:
              type: com.zendesk.ticket.tag.add
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: ZendeskTarget
              name: zendesk
      options:
        enableResync: false
    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: ZendeskTarget
        metadata:
          name: zendesk
        spec:
          email: <your-email>
          subdomain: <your-subdomain>
          token:
            secretKeyRef:
              key: token
              name: zendesk-api
      options:
        enableResync: false
